### ISSUE TITLE
Log gets spammed

### ISSUE THREAD

**Issue by cherry-wave** [adrielcafe/NMSAlphabetAndroidApp#1]
It's just on warn-level but spams the log a lot (multple times in just one milisecond):

```
05-02 20:14:29.456 29895-30001/cafe.adriel.nmsalphabet.free W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
```

**Comment by adrielcafe** [comment]
It's a related issue with [Glide](https://github.com/bumptech/glide) when it loads a gif, just happens on SplashActivity
[https://github.com/bumptech/glide/issues/743](https://github.com/bumptech/glide/issues/743)

Unfortunately I haven't found a way to disable the log :(

**Comment by adrielcafe** [comment]
Best solution I found is hide the irrelevant log:

1 - Android Monitor > Logcat > Edit Filter Configuration
![captura de tela 2016-05-03 as 14 05 25](https://cloud.githubusercontent.com/assets/2512298/14991671/ea4b7456-1138-11e6-93ab-83d7a8652466.png)

2 - Insert this string in Log Message
`^(?!Called reconfigure on a bitmap that is in use)`

![captura de tela 2016-05-03 as 14 07 51](https://cloud.githubusercontent.com/assets/2512298/14991680/f09fc4ec-1138-11e6-8b29-cc2c56be530e.png)
