### ISSUE TITLE
Error on app start

### ISSUE THREAD

**Issue by cherry-wave** [adrielcafe/NMSAlphabetAndroidApp#3]
```
05-02 20:13:39.122 29895-29933/cafe.adriel.nmsalphabet.free E/Fabric: Unknown error while loading Crashlytics settings. Crashes will be cached until settings can be retrieved.
05-02 20:13:39.125 29895-29933/cafe.adriel.nmsalphabet.free E/Answers: Failed to retrieve settings
```

**Comment by adrielcafe** [comment]
Seems a problem with phone's network connection:
- Proxies or some specific port settings
- Airplane mode
- Adblockers

Can you check these things and then clean and run the project again? **Waiting for response.**

Source: 
[https://twittercommunity.com/t/android-studio-unknown-error-while-loading-crashlytics-settings/58363](https://twittercommunity.com/t/android-studio-unknown-error-while-loading-crashlytics-settings/58363)
[http://stackoverflow.com/questions/32267041/android-failed-to-connect-to-settings-crashlytics-com-54-83-49-38-port-443-a](http://stackoverflow.com/questions/32267041/android-failed-to-connect-to-settings-crashlytics-com-54-83-49-38-port-443-a)
[http://stackoverflow.com/questions/27510889/fail-to-retrieve-settings-from-crashlytics](http://stackoverflow.com/questions/27510889/fail-to-retrieve-settings-from-crashlytics)
[http://stackoverflow.com/questions/30925747/crashlytics-initialization-connectionexception-ehostunreach](http://stackoverflow.com/questions/30925747/crashlytics-initialization-connectionexception-ehostunreach)

**Comment by adrielcafe** [comment]
Well, I managed to reproduce the issue.
I'm checking if the phone is connected, if not I don't start Fabric (with Crashlytics and Answers).

**Comment by cherry-wave** [comment]
OK, no error anymore! Thanks.
